language: node_js
node_js:
    - "8.9.4"
script:
    - "npm install -g pxt"
    - "pxt target arcade"
    - "pxt install --hw rpi"
    - "pxt build --hw rpi"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules